---
title: "Figure-it-out-markdown"
author: "Trevor Kapuvari & Timothy Oliver"
date: "15 December 2023"
output:
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---


```{r clear_environment, include=F, results = 'hide'}
rm(list=ls())
```


```{r setup, include=FALSE}

# global options for knitting chunks
local({
  hook_output <- knitr::knit_hooks$get('output')
  knitr::knit_hooks$set(output = function(x, options) {
    if (!is.null(options$max.height)) options$attr.output <- c(
      options$attr.output,
      sprintf('style="max-height: %s;"', options$max.height)
    )
    hook_output(x, options)
  })
})
knitr::opts_chunk$set(echo = TRUE,message=F,warning=F)



library(summarytools)
library(stargazer)
library(vtable)
library(tidyverse)
library(tidycensus)
library(sf)
library(spdep)
library(caret)
library(ckanr)
library(FNN)
library(grid)
library(gridExtra)
library(ggcorrplot) # plot correlation plot
library(corrr)      # another way to plot correlation plot
library(kableExtra)
library(jtools)     # for regression model plots
library(ggstance) # to support jtools plots
library(ggpubr)    # plotting R^2 value on ggplot point scatter
library(broom.mixed) # needed for effects plots
library(tufte)
library(viridis)
library(RSocrata)
library(classInt)
library(spatstat)
library(pscl)
library(plotROC)
library(pROC)
library(lubridate)
library(ROSE)
library(tigris)
library(knitr)
library(RSocrata)


# functions and data directory
root.dir = "https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/DATA/"


source("https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/functions.r")
source("themes/plotTheme_TO.r")
# source("functions/quantileBreaks.r")

palette2 <- c("#981FAC","#FF006A")
palette5 <- c("#25CB10", "#5AB60C", "#8FA108",   "#C48C04", "#FA7800")
palette5a <- c("#eff3ff","#bdd7e7","#6baed6","#3182bd","#08519c")
palette4a <- c("#D2FBD4","#92BCAB","#527D82","#123F5A")
palette2a <- c("#6baed6","#08519c")

palette9 <- viridis(9)

options(scipen=999)

```

# Here We Go

To download the data, go [here](https://www.kaggle.com/datasets/pranavbadami/nj-transit-amtrak-nec-performance/) using the button in the top-right and place the zip file in the data folder. The `kaggle_data` chunk should handle the rest.

```{r kaggle_data, results='hide'}
if (!dir.exists("data/Kaggle_transit&amtrak_data/")){
unzip("data/Kaggle_transit&amtrak_data.zip",exdir="data/Kaggle_transit&amtrak_data")
}

datApr2020 <- read.csv("data/Kaggle_transit&amtrak_data/2020_04.csv")
datMay2020 <- read.csv("data/Kaggle_transit&amtrak_data/2020_05.csv")


datApr2020 <- datApr2020 %>%
  mutate(interval60 = floor_date(ymd_hms(scheduled_time), unit = "hour"),
         interval15 = floor_date(ymd_hms(scheduled_time), unit = "15 mins"),
         interval1 = floor_date(ymd_hms(scheduled_time), unit = "min"),
         week = week(interval60),
         dotw = wday(interval60,label=T),
         delayed = ifelse(delay_minutes > 0,TRUE,FALSE))

datMay2020 <- datMay2020 %>%
  mutate(interval60 = floor_date(ymd_hms(scheduled_time), unit = "hour"),
         interval15 = floor_date(ymd_hms(scheduled_time), unit = "15 mins"),
         interval1 = floor_date(ymd_hms(scheduled_time), unit = "min"),
         week = week(interval60),
         dotw = wday(interval60,label=T),
         delayed = ifelse(delay_minutes > 0,TRUE,FALSE))

nj_trans_stations <- st_read("data/Rail_Stations_of_NJ_Transit.geojson")%>% st_transform(crs="ESRI:102711")

## !!!
### WE LOSE 27 STATIONS BY MERGING THE NAMES TO THE POINT DATA
## !!!

may_w_stations <- merge(x= nj_trans_stations,y=datMay2020,by.x="STATION_ID",by.y="from")%>%
  rename(from_station = STATION_ID,
         fromLat = LATITUDE, fromLon = LONGITUDE, 
         from_atis_id = ATIS_ID, from_muni = MUNICIPALITY,
         from_rail_service = RAIL_SERVICE,
         from_line_code = LINE_CODE)%>%
  select(-OBJECTID_1)%>%
  st_drop_geometry()%>%
  merge(y=nj_trans_stations,by.x="to",by.y="STATION_ID")%>%
  rename(toLat = LATITUDE, toLon = LONGITUDE, 
         to_atis_id = ATIS_ID, to_muni = MUNICIPALITY,
         to_rail_service = RAIL_SERVICE,
         to_line_code = LINE_CODE) %>%
  select(-OBJECTID_1)%>%
  st_drop_geometry() 

```

```{r simple_map, results='hide'}
census <- 
  get_acs(geography = "state", 
          variables = c("B01003_001", "B19013_001", 
                        "B02001_002", "B08013_001",
                        "B08012_001", "B08301_001", 
                        "B08301_010", "B01002_001"), 
          year = 2021, 
          geometry = TRUE, 
          output = "wide") %>%
  rename(Total_Pop =  B01003_001E,
         Med_Inc = B19013_001E,
         Med_Age = B01002_001E,
         White_Pop = B02001_002E,
         Travel_Time = B08013_001E,
         Num_Commuters = B08012_001E,
         Means_of_Transport = B08301_001E,
         Total_Public_Trans = B08301_010E)%>%
  st_transform(crs="EPSG:4326")


```

```{r view_stations}

ggplot()+
  geom_sf(data=census%>%filter(NAME=="New Jersey"|NAME=="Pennsylvania"|NAME=="New York")%>%st_transform(st_crs(nj_trans_stations)),color = "white",fill=GRAY9)+
            geom_sf(data=nj_trans_stations,color="lightblue")+
  plotTheme()+
  theme(panel.background=element_rect(
        fill = "#fcfcf4",
        colour = NA),
        panel.grid.major=element_blank(),
        axis.text=element_blank())

```

## Exploratory Analysis

```{r plots}

ggplot(may_w_stations %>%
         group_by(interval60) %>%
         tally())+
  geom_line(aes(x = interval60, y = n))+
  labs(title="Train Trips in NYC Area, May, 2020",
       x="Date", 
       y="Number of trips")+
  plotTheme()+
  coord_cartesian(ylim=c(0,300))

ggplot(may_w_stations)+
  geom_bar(aes(x=delayed,fill=delayed,show.legend=F))+
  labs(title="Delayed Train Trip Density in NYC Area, May, 2020",
       y="Number of trips")+
  plotTheme()

```

```{r from_station}
ggplot(may_w_stations %>%
         group_by(interval60, from_station) %>%
         tally())+
  geom_histogram(aes(n), binwidth = 1, color = GRAY8)+
  labs(title="Train trips per hr by station. NJTransit & Amtrak Area, May, 2020",
       x="Trip Counts", 
       y="Number of Stations")+
  plotTheme()+
  coord_cartesian(xlim=c(0,10))
```